### ISSUE TITLE
Need to check that number of attractor states does not exceed the total number of possible states

### ISSUE THREAD

**Issue by bcdaniels** [EnricoBorriello/AttAttach#3]

**Comment by EnricoBorriello** [comment]
The code now checks condition
1: The sum of the relative basin sizes needs to be 1;
and these additional ones (in doubt when n is very small);
2: All basins have at least size 1 (because for small n and small relative sizes, the product might result in zero states);
3: There are at least as many states as attractor states;
4: There are at least as many states as attractor states *in each individual basin*.
